FROM python:3.5-slim

RUN mkdir -p /usr/src/app
COPY web /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update && apt-get -y --no-install-recommends install curl vim telnet net-tools bash
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt-get install nodejs -y
RUN npm install -g webpack
# TODO this should be global but I ran into issues with some npm packages
RUN npm install
RUN webpack
